FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --package-lock=false
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/src/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
